modLoader="lowcodefml"
loaderVersion="[59,)"
license="MIT"

[[mods]]
modId="better_unpackables"
version="3.0.0-beta"
displayName="Better Unpackables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/better-unpackables"
credits="https://github.com/Classic36-Media/Better-Unpackables/wiki/Credits"
authors="Classic36"
description="Adds some quality-of-life unpacking recipes to the game."

[[dependencies.better_unpackables]]
    modId="forge"
    mandatory=true
    versionRange="[59,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_unpackables]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.9]"
    ordering="AFTER"
    side="BOTH"