modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="better_unpackables"
version="3.2.0-beta"
displayName="Better Unpackables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/better-unpackables"
credits="https://github.com/Classics-Craftworks/Better-Unpackables/wiki/Credits"
authors="Classic36"
description="Adds some quality-of-life unpacking recipes to the game."

[[dependencies.better_unpackables]]
    modId="neoforge"
    type="required"
    versionRange="[21.9.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_unpackables]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.9,26.1]"
    ordering="AFTER"
    side="BOTH"